
title: Gaze Demo
description: Documentation for Gaze Demo
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template